https://archive.ics.uci.edu/ml/datasets/Iris

In [14]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

In [15]:
iris_data = pd.read_csv('iris.data.txt', header=None)
iris_data.columns = ['Sepal length','Sepal width', 'Petal length', 'Petal width','Class']

In [16]:
iris_data.head()

Sepal length  Sepal width  Petal length  Petal width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [17]:
X = iris_data[['Sepal length','Sepal width', 'Petal length', 'Petal width']]
y = iris_data['Class']

In [18]:
# build train and test dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 100)

In [19]:
# Now it's time to train a Support Vector Machine Classifier. 
# Call the SVC() model from sklearn and fit the model to the training data.
from sklearn.svm import SVC
model=SVC(C=1, kernel='rbf', tol=0.001)
model.fit(X_train, y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [20]:
# Now get predictions from the model and create a confusion matrix and a classification report.
pred = model.predict(X_test)

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score


print(confusion_matrix(y_test, pred))
print('\n')
print(classification_report(y_test, pred))
print('\n')
print('Accuracy score is: ', accuracy_score(y_test, pred))

[[22  0  0]
 [ 0 15  0]
 [ 0  0 23]]


                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        22
Iris-versicolor       1.00      1.00      1.00        15
 Iris-virginica       1.00      1.00      1.00        23

    avg / total       1.00      1.00      1.00        60



Accuracy score is:  1.0
